import { createVuetify } from 'vuetify'
import * as components from 'vuetify/components'
import * as directives from 'vuetify/directives'
import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'

export default defineNuxtPlugin(nuxtApp => {
  const vuetify = createVuetify({
    ssr: true,
    components,
    directives,
    icons: {
      defaultSet: 'mdi',
    },
    theme: {
      defaultTheme: 'light',
      themes: {
        light: {
          colors: {
            primary: '#0b4c1a',
            secondary: '#ffffff',
            accent: '#4caf50',
            error: '#f44336',
            warning: '#ff9800',
            info: '#2196f3',
            success: '#4caf50',
            background: '#f8f9fa',
            surface: '#ffffff',
            navtext: '#000000',
            text: '#ffffff',
            'on-primary': '#ffffff',
            'on-secondary': '#000000',
            'on-background': '#1f1f1f',
            'on-surface': '#1f1f1f',
            'primary-darken-1': '#064113',
            'secondary-lighten-1': '#f5f5f5',
            'section-title': '#2e7d32',
            'section-subtitle': '#666666',
            'product-description': '#555555',
            'announcement-title': '#ffffff',
            'announcement-date': '#ffffff',
            'announcement-overlay-start': 'rgba(0, 0, 0, 0.3)',
            'announcement-overlay-end': 'rgba(0, 0, 0, 0.8)',
            'hero-overlay': 'rgba(0, 0, 0, 0.4)',
            'hero-text-shadow': 'rgba(0, 0, 0, 0.5)',
            'hero-arrow-bg': 'rgba(255, 255, 255, 0.2)',
            'hero-arrow-bg-hover': 'rgba(255, 255, 255, 0.3)',
            'footer-text-secondary': '#e8f5e8',
            'footer-link-hover': '#4caf50',
            'footer-border': '#2e7d32',
            'footer-social-btn-bg': 'rgba(76, 175, 80, 0.1)',
            'announcement-shadow': 'rgba(0, 0, 0, 0.15)',
            'product-card-shadow': 'rgba(0, 0, 0, 0.15)',
            'about-text': '#424242',
            'contact-title': '#2e7d32',
            'toggle-btn': 'rgba(0, 0, 0, 0.2)',
            'toggle-btn:hover': 'rgba(255, 255, 255, 0.1)',
            'title-main': '#0f2e37',
            'title-subtitle': '#2e7d32',
            'divider-line': '#61b96b',
            'card-shadow': 'rgba(0, 0, 0, 0.1)',
            'card-shadow-hover': 'rgba(0, 0, 0, 0.2)',
            'nav-button-bg': 'rgba(255, 255, 255, 0.95)',
            'nav-button-text': '#1e293b',
            'nav-button-shadow': 'rgba(0, 0, 0, 0.15)',
            'nav-button-shadow-hover': 'rgba(0, 0, 0, 0.2)',
            'dot-inactive': '#cbd5e1',
            'dot-hover': '#94a3b8',
            'dot-active': '#10b981',
            'dot-active-bg': 'rgba(16, 185, 129, 0.2)',
            'dot-hover-bg': 'rgba(16, 185, 129, 0.3)',
            'circle-ring': '#92E9FF',
            'vision-mission-eyebrow': '#2a6b7a',
            'vision-mission-title': '#083b43',
            'vision-mission-card-bg': '#eefdff',
            'vision-mission-card-shadow': 'rgba(0,0,0,.06)',
            'vision-mission-namebar-bg': '#10a5c2',
            'vision-mission-text': '#0f2e36',
            'vision-mission-card-highlight': 'rgba(255,255,255,.6)',
          }
        },
        dark: {
          colors: {
            primary: '#121212',
            secondary: '#ffffff',
            accent: '#81c784',
            error: '#cf6679',
            warning: '#ffb74d',
            info: '#64b5f6',
            success: '#81c784',
            background: '#1E1E1E',
            surface: '#1e1e1e',
            navtext: '#ffffff',
            text: '#ffffff',
            'on-primary': '#ffffff',
            'on-secondary': '#000000',
            'on-background': '#ffffff',
            'on-surface': '#ffffff',
            'section-title': '#81c784',
            'section-subtitle': '#b0b0b0',
            'product-description': '#cccccc',
            'announcement-title': '#ffffff',
            'announcement-date': '#e0e0e0',
            'announcement-overlay-start': 'rgba(0, 0, 0, 0.4)',
            'announcement-overlay-end': 'rgba(0, 0, 0, 0.9)',
            'hero-title': '#ffffff',
            'hero-overlay': 'rgba(0, 0, 0, 0.5)',
            'hero-text-shadow': 'rgba(0, 0, 0, 0.7)',
            'hero-arrow-bg': 'rgba(255, 255, 255, 0.25)',
            'hero-arrow-bg-hover': 'rgba(255, 255, 255, 0.4)',
            'footer-text-secondary': '#b0b0b0',
            'footer-link': '#ffffff',
            'footer-link-hover': '#4caf50',
            'footer-border': '#333333',
            'footer-social-btn-bg': 'rgba(76, 175, 80, 0.1)',
            'announcement-shadow': 'rgba(0, 0, 0, 0.25)',
            'product-card-shadow': 'rgba(0, 0, 0, 0.25)',
            'about-text': '#e0e0e0',
            'contact-title': '#ffffff',
            'toggle-btn': 'rgba(0, 0, 0, 0.2)',
            'toggle-btn:hover': 'rgba(255, 255, 255, 0.1)',
            'title-main': '#ffffff',
            'title-subtitle': '#81c784',
            'divider-line': '#81c784',
            'card-shadow': 'rgba(0, 0, 0, 0.3)',
            'card-shadow-hover': 'rgba(0, 0, 0, 0.4)',
            'nav-button-bg': 'rgba(45, 45, 45, 0.95)',
            'nav-button-text': '#ffffff',
            'nav-button-shadow': 'rgba(0, 0, 0, 0.3)',
            'nav-button-shadow-hover': 'rgba(0, 0, 0, 0.4)',
            'dot-inactive': '#4a5568',
            'dot-hover': '#718096',
            'dot-active': '#68d391',
            'dot-active-bg': 'rgba(104, 211, 145, 0.2)',
            'dot-hover-bg': 'rgba(104, 211, 145, 0.3)',
            'circle-ring': '#92E9FF',
            'vision-mission-eyebrow': '#4dd0e1',
            'vision-mission-title': '#e0f2f1',
            'vision-mission-card-bg': '#2d3748',
            'vision-mission-card-shadow': 'rgba(0,0,0,.3)',
            'vision-mission-namebar-bg': '#0891b2',
            'vision-mission-text': '#e2e8f0',
            'vision-mission-card-highlight': 'rgba(255,255,255,.1)',
          },
        },
      },
    },
    defaults: {
      VBtn: {
        style: 'text-transform: none;',
        variant: 'flat',
      },
      VCard: {
        elevation: 2,
      },
      VTextField: {
        variant: 'outlined',
        density: 'comfortable',
      },
      VSelect: {
        variant: 'outlined',
        density: 'comfortable',
      },
    },
  })

  nuxtApp.vueApp.use(vuetify)
})